use serde::Deserialize;

use crate::entities::player::Merged;

#[derive(Deserialize, Debug)]
pub struct PlayerGameInfo {
    #[serde(rename = "Account_Level")]
    pub account_level: u32,
    #[serde(rename = "ActiveId1")]
    pub active_id1: u32,
    #[serde(rename = "ActiveId2")]
    pub active_id2: u32,
    #[serde(rename = "ActiveId3")]
    pub active_id3: u32,
    #[serde(rename = "ActiveId4")]
    pub active_id4: u32,
    #[serde(rename = "ActivePlayerId")]
    pub active_player_id: String,
    #[serde(rename = "Assists")]
    pub assists: u32,
    #[serde(rename = "Ban1")]
    pub ban1: String,
    #[serde(rename = "Ban10")]
    pub ban10: String,
    #[serde(rename = "Ban10Id")]
    pub ban10_id: u32,
    #[serde(rename = "Ban11")]
    pub ban11: String,
    #[serde(rename = "Ban11Id")]
    pub ban11_id: u32,
    #[serde(rename = "Ban12")]
    pub ban12: String,
    #[serde(rename = "Ban12Id")]
    pub ban12_id: u32,
    #[serde(rename = "Ban1Id")]
    pub ban1_id: u32,
    #[serde(rename = "Ban2")]
    pub ban2: String,
    #[serde(rename = "Ban2Id")]
    pub ban2_id: u32,
    #[serde(rename = "Ban3")]
    pub ban3: String,
    #[serde(rename = "Ban3Id")]
    pub ban3_id: u32,
    #[serde(rename = "Ban4")]
    pub ban4: String,
    #[serde(rename = "Ban4Id")]
    pub ban4_id: u32,
    #[serde(rename = "Ban5")]
    pub ban5: String,
    #[serde(rename = "Ban5Id")]
    pub ban5_id: u32,
    #[serde(rename = "Ban6")]
    pub ban6: String,
    #[serde(rename = "Ban6Id")]
    pub ban6_id: u32,
    #[serde(rename = "Ban7")]
    pub ban7: String,
    #[serde(rename = "Ban7Id")]
    pub ban7_id: u32,
    #[serde(rename = "Ban8")]
    pub ban8: String,
    #[serde(rename = "Ban8Id")]
    pub ban8_id: u32,
    #[serde(rename = "Ban9")]
    pub ban9: String,
    #[serde(rename = "Ban9Id")]
    pub ban9_id: u32,
    #[serde(rename = "Camps_Cleared")]
    pub camps_cleared: u32,
    #[serde(rename = "Conquest_Losses")]
    pub conquest_losses: u32,
    #[serde(rename = "Conquest_Points")]
    pub conquest_points: u32,
    #[serde(rename = "Conquest_Tier")]
    pub conquest_tier: u32,
    #[serde(rename = "Conquest_Wins")]
    pub conquest_wins: u32,
    #[serde(rename = "Damage_Bot")]
    pub damage_bot: u32,
    #[serde(rename = "Damage_Done_In_Hand")]
    pub damage_done_in_hand: u32,
    #[serde(rename = "Damage_Done_Magical")]
    pub damage_done_magical: u32,
    #[serde(rename = "Damage_Done_Physical")]
    pub damage_done_physical: u32,
    #[serde(rename = "Damage_Mitigated")]
    pub damage_mitigated: u32,
    #[serde(rename = "Damage_Player")]
    pub damage_player: u32,
    #[serde(rename = "Damage_Taken")]
    pub damage_taken: u32,
    #[serde(rename = "Damage_Taken_Magical")]
    pub damage_taken_magical: u32,
    #[serde(rename = "Damage_Taken_Physical")]
    pub damage_taken_physical: u32,
    #[serde(rename = "Deaths")]
    pub deaths: u32,
    #[serde(rename = "Distance_Traveled")]
    pub distance_traveled: u32,
    #[serde(rename = "Duel_Losses")]
    pub duel_losses: u32,
    #[serde(rename = "Duel_Points")]
    pub duel_points: u32,
    #[serde(rename = "Duel_Tier")]
    pub duel_tier: u32,
    #[serde(rename = "Duel_Wins")]
    pub duel_wins: u32,
    #[serde(rename = "Entry_Datetime")]
    pub entry_datetime: String,
    #[serde(rename = "Final_Match_Level")]
    pub final_match_level: u32,
    #[serde(rename = "First_Ban_Side")]
    pub first_ban_side: String,
    #[serde(rename = "GodId")]
    pub god_id: u32,
    #[serde(rename = "Gold_Earned")]
    pub gold_earned: u32,
    #[serde(rename = "Gold_Per_Minute")]
    pub gold_per_minute: u32,
    #[serde(rename = "Healing")]
    pub healing: u32,
    #[serde(rename = "Healing_Bot")]
    pub healing_bot: u32,
    #[serde(rename = "Healing_Player_Self")]
    pub healing_player_self: u32,
    #[serde(rename = "ItemId1")]
    pub item_id1: u32,
    #[serde(rename = "ItemId2")]
    pub item_id2: u32,
    #[serde(rename = "ItemId3")]
    pub item_id3: u32,
    #[serde(rename = "ItemId4")]
    pub item_id4: u32,
    #[serde(rename = "ItemId5")]
    pub item_id5: u32,
    #[serde(rename = "ItemId6")]
    pub item_id6: u32,
    #[serde(rename = "Item_Active_1")]
    pub item_active_1: String,
    #[serde(rename = "Item_Active_2")]
    pub item_active_2: String,
    #[serde(rename = "Item_Active_3")]
    pub item_active_3: String,
    #[serde(rename = "Item_Active_4")]
    pub item_active_4: String,
    #[serde(rename = "Item_Purch_1")]
    pub item_purch_1: String,
    #[serde(rename = "Item_Purch_2")]
    pub item_purch_2: String,
    #[serde(rename = "Item_Purch_3")]
    pub item_purch_3: String,
    #[serde(rename = "Item_Purch_4")]
    pub item_purch_4: String,
    #[serde(rename = "Item_Purch_5")]
    pub item_purch_5: String,
    #[serde(rename = "Item_Purch_6")]
    pub item_purch_6: String,
    #[serde(rename = "Joust_Losses")]
    pub joust_losses: u32,
    #[serde(rename = "Joust_Points")]
    pub joust_points: u32,
    #[serde(rename = "Joust_Tier")]
    pub joust_tier: u32,
    #[serde(rename = "Joust_Wins")]
    pub joust_wins: u32,
    #[serde(rename = "Killing_Spree")]
    pub killing_spree: u32,
    #[serde(rename = "Kills_Bot")]
    pub kills_bot: u32,
    #[serde(rename = "Kills_Double")]
    pub kills_double: u32,
    #[serde(rename = "Kills_Fire_Giant")]
    pub kills_fire_giant: u32,
    #[serde(rename = "Kills_First_Blood")]
    pub kills_first_blood: u32,
    #[serde(rename = "Kills_Gold_Fury")]
    pub kills_gold_fury: u32,
    #[serde(rename = "Kills_Penta")]
    pub kills_penta: u32,
    #[serde(rename = "Kills_Phoenix")]
    pub kills_phoenix: u32,
    #[serde(rename = "Kills_Player")]
    pub kills_player: u32,
    #[serde(rename = "Kills_Quadra")]
    pub kills_quadra: u32,
    #[serde(rename = "Kills_Siege_Juggernaut")]
    pub kills_siege_juggernaut: u32,
    #[serde(rename = "Kills_Single")]
    pub kills_single: u32,
    #[serde(rename = "Kills_Triple")]
    pub kills_triple: u32,
    #[serde(rename = "Kills_Wild_Juggernaut")]
    pub kills_wild_juggernaut: u32,
    #[serde(rename = "Map_Game")]
    pub map_game: String,
    #[serde(rename = "Mastery_Level")]
    pub mastery_level: u32,
    #[serde(rename = "Match")]
    pub match_id: u64,
    #[serde(rename = "Match_Duration")]
    pub match_duration: u32,
    #[serde(rename = "MergedPlayers")]
    pub merged_players: Option<Vec<Merged>>,
    #[serde(rename = "Minutes")]
    pub minutes: u32,
    #[serde(rename = "Multi_kill_Max")]
    pub multi_kill_max: u32,
    #[serde(rename = "Objective_Assists")]
    pub objective_assists: u32,
    #[serde(rename = "PartyId")]
    pub party_id: u64,
    #[serde(rename = "Rank_Stat_Conquest")]
    pub rank_stat_conquest: f64,
    #[serde(rename = "Rank_Stat_Duel")]
    pub rank_stat_duel: f64,
    #[serde(rename = "Rank_Stat_Joust")]
    pub rank_stat_joust: f64,
    #[serde(rename = "Reference_Name")]
    pub reference_name: String,
    #[serde(rename = "Region")]
    pub region: String,
    #[serde(rename = "Role")]
    pub role: String,
    #[serde(rename = "Skin")]
    pub skin: String,
    #[serde(rename = "SkinId")]
    pub skin_id: u32,
    #[serde(rename = "Structure_Damage")]
    pub structure_damage: u32,
    #[serde(rename = "Surrendered")]
    pub surrendered: u32,
    #[serde(rename = "TaskForce")]
    pub task_force: u32,
    #[serde(rename = "Team1Score")]
    pub team1_score: u32,
    #[serde(rename = "Team2Score")]
    pub team2_score: u32,
    #[serde(rename = "TeamId")]
    pub team_id: u32,
    #[serde(rename = "Team_Name")]
    pub team_name: String,
    #[serde(rename = "Time_Dead_Seconds")]
    pub time_dead_seconds: u32,
    #[serde(rename = "Time_In_Match_Seconds")]
    pub time_in_match_seconds: u32,
    #[serde(rename = "Towers_Destroyed")]
    pub towers_destroyed: u32,
    #[serde(rename = "Wards_Placed")]
    pub wards_placed: u32,
    #[serde(rename = "Win_Status")]
    pub win_status: String,
    #[serde(rename = "Winning_TaskForce")]
    pub winning_task_force: u32,
    #[serde(rename = "hasReplay")]
    pub has_replay: String,
    #[serde(rename = "hz_gamer_tag")]
    pub hz_gamer_tag: Option<String>,
    #[serde(rename = "hz_player_name")]
    pub hz_player_name: String,
    #[serde(rename = "match_queue_id")]
    pub match_queue_id: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "playerId")]
    pub player_id: String,
    #[serde(rename = "playerName")]
    pub player_name: String,
    #[serde(rename = "playerPortalId")]
    pub player_portal_id: Option<String>,
    #[serde(rename = "playerPortalUserId")]
    pub player_portal_user_id: Option<String>,
    #[serde(rename = "ret_msg")]
    pub ret_msg: Option<String>,
}

impl PlayerGameInfo {
    #[must_use]
    pub fn bought_items(&self) -> Vec<(&str, u32)> {
        [
            (self.item_purch_1.as_str(), self.item_id1),
            (self.item_purch_2.as_str(), self.item_id2),
            (self.item_purch_3.as_str(), self.item_id3),
            (self.item_purch_4.as_str(), self.item_id4),
            (self.item_purch_5.as_str(), self.item_id5),
            (self.item_purch_6.as_str(), self.item_id6),
        ]
        .into_iter()
        .filter(|(name, _)| !name.trim().is_empty())
        .collect()
    }

    #[must_use]
    pub fn has_won(&self) -> bool {
        self.win_status == "Winner"
    }
}
